# Generated by Django 5.1.6 on 2025-04-25 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, default='logos/default-img.jpg', upload_to='products')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_publico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('lt', 'Litros'), ('unidad', 'Unidad')], max_length=20)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('agotado', 'Agotado'), ('descontinuado', 'Descontinuado')], default='activo', max_length=20)),
                ('control_stock', models.BooleanField(default=True)),
                ('motivo_actualizacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.proveedor')),
            ],
        ),
    ]
