# Generated by Django 5.2.8 on 2026-03-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='control_stock',
            new_name='perecedero',
        ),
    ]
