# Generated by Django 5.1.6 on 2025-04-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag_default', models.ImageField(blank=True, upload_to='logos/')),
                ('title1', models.CharField(blank=True, max_length=50)),
                ('title2', models.CharField(blank=True, max_length=50)),
                ('title3', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('width', models.PositiveIntegerField(blank=True, default=150)),
                ('height', models.PositiveIntegerField(blank=True, default=40)),
                ('carousel_image_1', models.ImageField(blank=True, upload_to='carousel/')),
                ('carousel_image_1_title', models.CharField(blank=True, max_length=50)),
                ('carousel_image_1_text', models.CharField(blank=True, max_length=300)),
                ('carousel_image_2', models.ImageField(blank=True, upload_to='carousel/')),
                ('carousel_image_2_title', models.CharField(blank=True, max_length=50)),
                ('carousel_image_2_text', models.CharField(blank=True, max_length=300)),
                ('carousel_image_3', models.ImageField(blank=True, upload_to='carousel/')),
                ('carousel_image_3_title', models.CharField(blank=True, max_length=50)),
                ('carousel_image_3_text', models.CharField(blank=True, max_length=300)),
                ('carousel_3_boton', models.CharField(blank=True, max_length=15)),
                ('tarjeta_1_imagen', models.ImageField(blank=True, upload_to='card/')),
                ('text1', models.CharField(blank=True, max_length=300)),
                ('tarjeta_2_imagen', models.ImageField(blank=True, upload_to='card/')),
                ('text2', models.CharField(blank=True, max_length=300)),
                ('tarjeta_3_imagen', models.ImageField(blank=True, upload_to='card/')),
                ('text3', models.CharField(blank=True, max_length=300)),
                ('presentation1_text_primary', models.CharField(blank=True, max_length=300)),
                ('presentation1_text_secundary', models.CharField(blank=True, max_length=300)),
                ('presentation1_text', models.CharField(blank=True, max_length=300)),
                ('presentation1_image', models.ImageField(blank=True, upload_to='presentation/')),
                ('presentation2_text_primary', models.CharField(blank=True, max_length=300)),
                ('presentation2_text_secundary', models.CharField(blank=True, max_length=300)),
                ('presentation2_text', models.CharField(blank=True, max_length=300)),
                ('presentation2_image', models.ImageField(blank=True, upload_to='presentation/')),
                ('presentation3_text_primary', models.CharField(blank=True, max_length=300)),
                ('presentation3_text_secundary', models.CharField(blank=True, max_length=300)),
                ('presentation3_text', models.CharField(blank=True, max_length=300)),
                ('presentation3_image', models.ImageField(blank=True, upload_to='presentation/')),
            ],
            options={
                'verbose_name_plural': 'Covers',
            },
        ),
    ]
