# Generated by Django 5.2.8 on 2025-11-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Introduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='carousel_image_1',
            field=models.ImageField(blank=True, default='carousel/default-img.jpg', upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='carousel_image_2',
            field=models.ImageField(blank=True, default='carousel/default-img.jpg', upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='carousel_image_3',
            field=models.ImageField(blank=True, default='carousel/default-img.jpg', upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='imag_default',
            field=models.ImageField(blank=True, default='logos/default-img.jpg', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='logo',
            field=models.ImageField(blank=True, default='logos/default-img.jpg', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='presentation1_image',
            field=models.ImageField(blank=True, default='presentation/default-img.jpg', upload_to='presentation/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='presentation2_image',
            field=models.ImageField(blank=True, default='presentation/default-img.jpg', upload_to='presentation/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='presentation3_image',
            field=models.ImageField(blank=True, default='presentation/default-img.jpg', upload_to='presentation/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='tarjeta_1_imagen',
            field=models.ImageField(blank=True, default='card/default-img.jpg', upload_to='card/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='tarjeta_2_imagen',
            field=models.ImageField(blank=True, default='card/default-img.jpg', upload_to='card/'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='tarjeta_3_imagen',
            field=models.ImageField(blank=True, default='card/default-img.jpg', upload_to='card/'),
        ),
    ]
